#!/usr/bin/env python
#
# This does some simple sanity checks on the configuration, and tries to print informative
# results of that check. Hopefully never dumping a python stack trace.
#

import sys
from sanity.checker import *

def main(args):

    checker = Checker()

    if not checker.checkOS():
        print 'I do not think we support your OS. Sorry.'
        return 1

    success = checker.checkCompiler()

    if success:
        checker.checkAuxiliaries()
    
    return 0 if success else 1
    

if __name__ == '__main__':
    sys.exit(main(sys.argv))


    
