#!/usr/bin/env python
#
# This does some simple sanity checks on the configuration, and tries to print informative
# results of that check. Hopefully never dumping a python stack trace.
#

import sys
import os
from sanity.checker import *

def main(args):

    
    if not (sys.platform.startswith('freebsd') or
             sys.platform.startswith('linux') or 
             sys.platform.startswith('darwin')):
        print 'I do not think we support your OS. Sorry.'
        return 1

    checker = Checker()


    success = checker.checkCompiler()

    if success:
        checker.checkAuxiliaries()
    
    return 0 if success else 1
    

if __name__ == '__main__':
    sys.exit(main(sys.argv))


    
