# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y python-pip
     sudo apt-get install -y llvm-3.5 clang-3.5
     sudo pip install wllvm
     echo 'export PATH=/usr/lib/llvm-3.5/bin:${PATH}' >> /home/vagrant/.bashrc
     echo 'export LLVM_COMPILER=clang'                >> /home/vagrant/.bashrc
     echo 'export WLLVM_OUTPUT=WARNING'               >> /home/vagrant/.bashrc
   SHELL

end
